
services:
    nginx:
        container_name: nginx
        build:
            context: ./requirements/nginx/.
            # no_cache: true
            tags:
                - nginx
        ports:
            - '443:443'
        networks:
            - inception_network
        volumes:
            - wordpress_data:${WP_PATH}:ro  #read only permission for files that are created by wordpress
        env_file:
            - .env
        depends_on:
            wordpress:
                condition: service_healthy
        init: true
        restart: always

    wordpress:
        container_name: wordpress
        build:
            context: ./requirements/wordpress/.
            # no_cache: true
            tags:
                - wordpress
        networks:
            - inception_network
        volumes:
            - wordpress_data:${WP_PATH}
        env_file:
            - .env
        depends_on:
            mariadb:
                condition: service_healthy
        healthcheck:
            test: ["CMD-SHELL", "mysql -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -h mariadb ${MYSQL_DATABASE} -e 'SELECT 1;'"]
            start_period: 7s
            interval: 2s
            timeout: 5s
            retries: 5
        init: true
        restart: always


    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb/.
            # no_cache: true
            tags:
                - mariadb
        env_file:
            - .env
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - inception_network
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -u ${MYSQL_ROOT_USER} -p${MYSQL_ROOT_PASSWORD}"]
            start_period: 7s
            interval: 2s
            timeout: 5s
            retries: 5
        init: true
        restart: always

networks:
    inception_network:
        name: inception_network

volumes:
    wordpress_data:
        driver: local
        driver_opts:
            type: none
            device: ${VOLUME_PATH}/wordpress
            o: bind
    mariadb_data:
        driver: local
        driver_opts:
            type: none
            device: ${VOLUME_PATH}/mariadb
            o: bind
